name: Flujo CI/CD Taller

on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  ci-testing:
    name: Pruebas (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Verificar existencia de archivos
        run: |
          if [ -f "pages/home.html" ] && [ -f "styles/styles.css" ]; then
            echo "Éxito: Los archivos home.html y styles.css existen."
          else
            echo "Error: Faltan archivos requeridos."
            exit 1
          fi

  cd-deployment:
    name: Preparación para el Despliegue (CD)
    needs: ci-testing
    runs-on: ubuntu-latest
    steps:
      - name: test despliegue
        run: echo "Artefactos listos para el despliegue en el entorno de Staging"